# importing the module 
import tweepy 

def Tweet(inpStr):
    # personal details 
    consumer_key ="<insert key here>"
    consumer_secret ="<insert secret here>"
    access_token ="<insert token here>"
    access_token_secret ="<insert secret token here>"
  
    # authentication of consumer key and secret 
    auth = tweepy.OAuthHandler(consumer_key, consumer_secret) 
  
    # authentication of access token and secret 
    auth.set_access_token(access_token, access_token_secret) 
    api = tweepy.API(auth) 
  
    # update the status 
    api.update_status(status = inpStr + "\n\n\nGenerated By BOT") 
